### ISSUE TITLE
Saving issue under Wordpress 4.7

### ISSUE THREAD

**Issue by asha23** [tylerdigital/draw-attention#1]
I'm getting a save issue when I change an image - Using Wordpress 4.7

My stack trace shows the following error.

Notice: Undefined index: action in {{my path}}/plugins/draw-attention/admin/class-drawattention-admin.php on line 352

**Comment by tylerdigital** [comment]
Thanks @asha23 for reporting this! we've just pushed a commit to fix it and will release the fix to wordpress.org
